### ISSUE TITLE
Android Application

### ISSUE THREAD

**Issue by dnlbaines** [evanbrumley/spyfall#10]
I'm an Android app developer and was wondering whether you would like me to release an app on Google Play for Spyfall. It will essentially be a webview so would just load your website but may allow people easier access to it/help it to gain more visibility.

**Comment by evanbrumley** [comment]
Hi Daniel, thanks for the offer! My preference at the moment is to keep clear of the mobile app space so that the original creators of Spyfall have the best possible run at making money out of their creation if they decide to do so. That's the main reason I've kept the styling and feature set very simple - it's tough making a living out of board and card games, and I really want to make sure that anything I do or encourage helps, rather than hinders them.

That said, if you want to have some fun and learn some cool stuff along the way, I thoroughly recommend having a play with my codebase and with Meteor's cordova/phonegap integration. Meteor is a really interesting platform for developing games, and the cordova support gives you much better results than a simple webview!

**Comment by dnlbaines** [comment]
Yeah that seems fair enough, and I'll certainly take a look at Meteor at some point. Thanks!

**Comment by shashvatshukla** [comment]
Would like to point out that it is currently very playable on mobile platforms.
