### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by dazinator** [evanbrumley/spyfall#28]
Thanks for a cool implementation!
Some thoughts / ideas for some possible features - what do you think about any of these:-

1. The ability to track which players turn it currently is (to ask a question.)
2. The ability to use some form of in game chat window - so that the game could be joined by a remote player (someone not presently in the room?)
3. The ability for the spy to "strike through" locations on the locations list as an aid for keeping track of which locations are suspected. (Memory aid)
4. The ability for the non spy's to strike through players who they think are not the spy. (Memory aid)

**Comment by evanbrumley** [comment]
Memory aids have now been added, courtesy of gavinksong! Don't let anyone see you ticking off locations :-)

Unfortunately, chat probably won't happen in the near future, simply because the tiny free server I'm running the game on can barely keep up with managing the current load (over 70,000+ games per day in peak periods!). As for a turn tracker, I'm not sure how we could implement that cleanly in a way that really added to the game. The official rules say that they person who just answered should be the one to ask the next question, so it would have to involve tapping on particular people's names as you asked them a question..
