### ISSUE TITLE
Blank pages

### ISSUE THREAD

**Issue by atari-lord** [evanbrumley/spyfall#37]
I tried to show some friends the game and all 4 of them got a blank screen when they reached the website. We tried refreshing, we tried different browser apps, we tried different networks and nothing worked. All android phones. My phone worked fine. Any advice?

**Comment by atari-lord** [comment]
Update. Just tried playing again with friends who have been able to use it in the past and 2 of them couldn't get it to work either.

**Comment by GioBonvi** [comment]
The same for me: the last time it worked correctly (I played with some friends) for me was 30/5
I opened the page last week and it displayed correctly,  but it could have been a cache copy, as I suspect it was for atari-lord

**Comment by evanbrumley** [comment]
Hi guys,

Thanks for much for reporting this! It turns out an update to Chrome caused issues with iron-router. See details here:

https://forums.meteor.com/t/solved-error-handler-with-name-u-already-exists/23910

I've just rolled out a fix, so the site should be back online for android/chrome users.

Cheers,

Ev
